#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/app/app.php';

$console = new \Symfony\Component\Console\Application();

$console->add($app['Application\Command\CreateUserCommand']);

$console->run();