#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/app/app.php';

$commands = array(
    'Application\Command\ServeCommand',
    'Application\Command\ExampleCommand'
);


$console = new \Symfony\Component\Console\Application();

array_map(function($commandName) use($app, $console){
    $app[$commandName]->setContainer($app);
    $console->add($app[$commandName]);
}, $commands);

$console->run();